stages:
  - deploy

#########################
#        Deploy         #
#########################

pages:
  stage: deploy
  tags:
    - linux
    - docker
  image: docker.io/library/busybox:latest
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - cp -r ./Container/ ./PublicKey/ ./ServerMaintenance/ ./Temp/ ./public/
  pages: true
  artifacts:
    paths:
      - ./public/
